/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatteryPage: typeof import('./src/components/BatteryPage.vue')['default']
    CartoonRig: typeof import('./src/components/CartoonRig.vue')['default']
    Customization: typeof import('./src/components/Customization.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
